baseurl = "http://thisdwhitley.com"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "thisdwhitley"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
googleAnalytics = "UA-134824864-1"

[permalinks]
  blog = "/:year/:month/:title/"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "my umpteenth attempt at capturing notes online"
#  logo = "img/avatar-icon.png"
  logo = "img/font-awesome_4-7-0_hand-o-down.png"
  favicon = "img/hand-o-down.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = true
  showRelatedPosts = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "thisdwhitley"
  website = "yourwebsite.com"
  email = "thisdwhitley@gmail.com"
#  facebook = "username"
#  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "thisdwhitley"
  gitlab = "thisdwhitley"
  bitbucket = "thisdwhitley"
  twitter = "thisdwhitley"
#  reddit = "username"
  linkedin = "thisdwhitley"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
#  telegram = "username"

[[menu.main]]
    name = "About"
    identifier = "about"
    url = "page/about/"
    weight = 1

[[menu.main]]
    parent = "about"
    name = "disclosure"
    url = "page/disclosure/"
    weight = 1

[[menu.main]]
    parent = "about"
    name = "me"
    url = "page/about/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    name = "Topics"
    identifier = "categories"
    url = "categories"
    weight = 5

[[menu.main]]
    parent = "categories"
    name = "house"
    url = "categories/house/"
    weight = 3

[[menu.main]]
    parent = "categories"
    name = "tech"
    url = "categories/tech/"
    weight = 4

[[menu.main]]
    parent = "categories"
    name = "truck"
    url = "categories/truck/"
    weight = 5

[[menu.main]]
    parent = "categories"
    name = "yard"
    url = "categories/yard/"
    weight = 6

[[menu.main]]
    name = "[OLD BLOGS]"
    url = "archive"
    weight = 7